spring:
  datasource:
    username: music
    password: 789233
    url: jdbc:mysql://localhost:3306/permissioncontroller?characterEncoding=UTF-8&seTimezone=true&serverTimezone=GMT%2B8&useSSL=false #设置时区 u
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource